/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzp_applicationkotlin_NDKTool */

#ifndef _Included_com_zzp_applicationkotlin_NDKTool
#define _Included_com_zzp_applicationkotlin_NDKTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzp_applicationkotlin_NDKTool
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzp_applicationkotlin_NDKTool_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
